### ISSUE TITLE
make package available on dante

### ISSUE THREAD

**Issue by hpvd** [michal-h21/linebreaker#2]
was pointed to this package from a discussion about
> Promoting other package which also **enhances LaTeX automatic typesetting quality to the next level** within in the doc
https://github.com/gucci-on-fleek/lua-widow-control/discussions/6

Since it exactly does what the discussion is about and it works like a charm for overfull boxes
(it lowered number of these by 12 within my long test document in fully automatic fashion)
=> would be awesome to have this package **directly on ctan** to make it easy for other users to find, install and use it :-)
https://ctan.org/search?phrase=linebreaker

PS: IMHO it's not a reason to wait any longer while thinking about more fine-tuning of its function, this would already be a great start

**Comment by michal-h21** [comment]
@hpvd I will need to creat some documentation, but otherwise I think I can release it. Thanks for the reminder.

**Comment by hpvd** [comment]
@michal-h21 
would be awesome!
Many thanks for your work!

**Comment by hpvd** [comment]
wow, just saw you are already working towards first release :-)

**Comment by michal-h21** [comment]
@hpvd yes, I am doing just last fixes in the documentation. I hope to post it today.

**Comment by michal-h21** [comment]
I've just uploaded the package to CTAN, so it should be available in TL soon.

**Comment by hpvd** [comment]
awesome - many thanks!

will close this issue...

**Comment by hpvd** [comment]
just to complete this topic: It just arrived at miktex packages...
