### ISSUE TITLE
[Bug] Wrong direction in bidirectional documents

### ISSUE THREAD

**Issue by amarakon** [michal-h21/linebreaker#7]
In issue #6, I mentioned how Arabic documents look wrong when using this package. This was fixed shortly after. However, a problem still persists. In bilingual documents where one language is left-to-right and the other language is right-to-left, both cannot work at the same time. If my main language is English and my secondary language is Arabic, the bottom line of the Arabic paragraph will be aligned to the left, when it should be aligned to the right. Similarly, if my main language is Arabic and my secondary language is English, the Arabic paragraph will be rendered correctly but the bottom line of the English paragraph will be aligned to the right instead of the left. Below, I have provided two minimum working examples that demonstrate this, along with the expected behaviour that happens when I don't load the `linebreaker` package.

```tex
\documentclass{article}

\usepackage{linebreaker, lipsum}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{english}
\babelprovide[import]{arabic}
\babelfont[arabic]{rm}{Amiri}

\begin{document}

\lipsum[1]

\begin{otherlanguage}{arabic}
	لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد
	الألم نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية،
	فلا أحد يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا
	يدركون بأن السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا
	لمواجهة الظروف الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ
	بالآلام، الألم هو الألم ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد
	وأسي.
\end{otherlanguage}

\end{document}
```

<img src="https://user-images.githubusercontent.com/92645199/223250862-71915b9f-645f-4f29-bed5-0cd7980210e5.png" width="100%" />

```tex
\documentclass{article}

\usepackage{linebreaker, lipsum}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{arabic}
\babelprovide[import]{english}
\babelfont[arabic]{rm}{Amiri}

\begin{document}

\begin{otherlanguage}{english}
\lipsum[1]
\end{otherlanguage}

لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.

\end{document}
```

<img src="https://user-images.githubusercontent.com/92645199/223252634-a06a7365-3d13-4717-ae1f-178073a9dd3d.png" width="100%" />

# Expected result

<img src="https://user-images.githubusercontent.com/92645199/223253020-b4eda27a-61ed-4cc9-9861-459a801db1a0.png" width="100%" />

**Comment by michal-h21** [comment]
This seems a bit strange. When Lineberak breaks this paragraph:

```
\begin{otherlanguage}{english}
\lipsum[1]
\end{otherlanguage}
```

it is marked in `tex.pardir` as `TRT`, which means that it should be right  to left paragraph. I don't understand why only the last line uses this direction.

Anyway, when I add a paragraph end inside `otherlanguage`, the paragraph gets a correct `pardir` information:

```
\documentclass{article}

\usepackage{linebreaker}
\usepackage{lipsum}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{arabic}
\babelprovide[import]{english}
\babelfont[arabic]{rm}{Amiri}

\begin{document}

\begin{otherlanguage}{english}
\lipsum[1]

\end{otherlanguage}

لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.

\end{document}
```

![obrazek](https://user-images.githubusercontent.com/504800/223410009-c15a189f-6766-42d8-8cf3-82b28eeb2bdb.png)

**Comment by amarakon** [comment]
> Anyway, when I add a paragraph end inside `otherlanguage`, the paragraph gets a correct `pardir` information.

Unfortunately, this workaround doesn't work within a `multicols` environment (from the `multicol` package) if I try to change the Roman font for English. Every page except for the last will be messed up:

```tex
\documentclass{book}

\usepackage{linebreaker}
\usepackage{lipsum}
\usepackage{multicol}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{english}
\babelprovide[import]{arabic}

\babelfont[english]{rm}{EB Garamond}
\babelfont[arabic]{rm}{Amiri}

\begin{document}

\begin{multicols}{2}
	\lipsum[1]

	\begin{otherlanguage}{arabic}
		لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
		نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
		يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
		السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
		الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
		ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.

	\end{otherlanguage}

	\lipsum[1]

	\begin{otherlanguage}{arabic}
		لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
		نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
		يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
		السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
		الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
		ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.

	\end{otherlanguage}

	\lipsum[1]

	\begin{otherlanguage}{arabic}
		لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
		نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
		يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
		السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
		الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
		ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.

	\end{otherlanguage}

	\lipsum[1]

	\begin{otherlanguage}{arabic}
		لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
		نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
		يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
		السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
		الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
		ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.

	\end{otherlanguage}
\end{multicols}

\end{document}
```

![test-1](https://user-images.githubusercontent.com/92645199/224142428-1308d3d5-fc86-4977-b2c3-cdfeaf72a21a.png)

![test-2](https://user-images.githubusercontent.com/92645199/224142431-81a88900-2cc1-4d05-a61f-4a04871f4fa7.png)

If you uncomment the line `\babelfont[english]{rm}{EB Garamond}`, it will work as expected.

**Comment by michal-h21** [comment]
Ah, that will need further investigation. Unfortunately, I received a bit too many bug reports this week, so it can take some time before I will have the capacity to do that :/

**Comment by amarakon** [comment]
Sure, no rush.

**Comment by michal-h21** [comment]
I've tried your Multicols MWE, and it seems that it produces this wrong result even if I remove Linebreaker altogether. Maybe it is rather  bug in Multicols, or in Babel?

**Comment by amarakon** [comment]
You’re right, the bug still happens without `linebreaker. What’s even more interesting is the fact that this bug only happens with the EB Garamond font. I tested it with other fonts and it worked completely fine. So the issue is not with `multicols` or `babel`, it’s with EB Garamond for some reason. I’m going to open an issue on https://github.com/georgd/EB-Garamond.

**Comment by hpvd** [comment]
just give it a few tries...

when using basic `\twocolumn` instead of loading `multicol` package plus `\begin{multicols}{2} ... \end{multicols}{2}`

enabling/disabling `linebreaker` package changes the alignment direction 

```
\documentclass{book}

%\usepackage{linebreaker}
\usepackage{lipsum}
%\usepackage{multicol}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{english}
\babelprovide[import]{arabic}

\babelfont[english]{rm}{EB Garamond}
\babelfont[arabic]{rm}{Amiri}

\begin{document}

%\begin{multicols}{2}
\twocolumn
	\lipsum[1-6]

	\begin{otherlanguage}{arabic}
		لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
		نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
		يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
		السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
		الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
		ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.

	\end{otherlanguage}
%\end{multicols}

\end{document}
```

**Comment by hpvd** [comment]
![2023-03-15_12h38_32](https://user-images.githubusercontent.com/5681880/225298926-bb195e7f-cdaa-4c31-944d-541d0e015de3.png)

**Comment by hpvd** [comment]
![2023-03-15_12h41_11](https://user-images.githubusercontent.com/5681880/225299003-8f83874c-3f04-4e5f-a9bd-2e3895a63eae.png)

**Comment by hpvd** [comment]
just to verify that not the autoamtic pagebreak makes the difference:
the alignment change by enable//disable `linebreaker` package keeps the same when you reduce the length of lipsum to `\lipsum[1-5]` to make it fit to one page (I'm using A4)

**Comment by hpvd** [comment]
hmm if you add another lipsum after the arabic part, strange things happen even without linebreaker package
```

\documentclass{book}

%\usepackage{linebreaker}
\usepackage{lipsum}
%\usepackage{multicol}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{english}
\babelprovide[import]{arabic}

\babelfont[english]{rm}{EB Garamond}
\babelfont[arabic]{rm}{Amiri}

\begin{document}

%\begin{multicols}{2}
\twocolumn
	\lipsum[1-7]

	\begin{otherlanguage}{arabic}
		لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
		نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
		يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
		السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
		الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
		ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.

	\end{otherlanguage}
	\lipsum[1-7]
%\end{multicols}

\end{document}
```

**Comment by michal-h21** [comment]
It seems that in the TRT context, Linebreaker causes the last line of a paragraph to be aligned to the left, instead of the right. Rest of the paragraph seems to be aligned correctly.

<img src="https://user-images.githubusercontent.com/5681880/225299003-8f83874c-3f04-4e5f-a9bd-2e3895a63eae.png" />

**Comment by hpvd** [comment]
to help on this topic, @amarakon started a discussion on tex.stackexchange.com
https://tex.stackexchange.com/questions/680079/some-fonts-do-not-work-properly-with-multicols-and-babel

**Comment by michal-h21** [comment]
I've found the source of the issue with Linebreaker.  It didn't pass the parameters table (which contained the info about `pardir`) to the line-breaking function when there was an overfull line in the paragraph. This is the reason why it was so random and why it happened with shorter line widths. The last update should fix that.

**Comment by hpvd** [comment]
could confirm enabling/disabling linebreaker and the RTL alignment keeps the same:
![2023-03-20_15h13_56](https://user-images.githubusercontent.com/5681880/226369083-69317ef2-3850-493f-ab8e-07bc1bb2fa2c.png)

**Comment by amarakon** [comment]
> could confirm enabling/disabling linebreaker and the RTL alignment keeps the same:...

Me too. I tested it and the paragraph direction is now correct. There is still the other issue of the whole text being shifted way far to the left until the last page.

**Comment by hpvd** [comment]
great, since the still existing issue seems to be a babel bug
see https://github.com/latex3/babel/issues/228

this one may be closed.

(with the option to reopen, if the upcoming babel fix will not solve it completely)

**Comment by hpvd** [comment]
of course it would be great to push a new release to ctan including this fix :-)

btw: on ctan one can see and obtain a newer release/tag/version than in this repository:

![2023-03-21_09h48_20](https://user-images.githubusercontent.com/5681880/226557445-30ad5218-04b8-41b1-ad6b-4564d54a3225.png)

**Comment by michal-h21** [comment]
Thanks for noticing. It seems that I didn't push tags from my other computer. I've fixed another issue regarding  the debug print, and updated CTAN.  I hope I can close this issue now :)

**Comment by hpvd** [comment]
there was already a fix implemented in babel and the issue was closed, see
https://github.com/latex3/babel/issues/228

could you @amarakon and @michal-h21 confirm, that this (latest linebreaker plus latest babel) make it work for you?
On my side things still looks strange...

**Comment by hpvd** [comment]
hmm adding \listfiles to tex file shows that I'm not using the latest babel version I have just installed.
Maybe because version keeps the same number...

**Comment by amarakon** [comment]
> could you @amarakon and @michal-h21 confirm, that this (latest linebreaker plus latest babel) make it work for you? On my side, things still look strange...

I can confirm that I am seeing the expected result. Are you using the latest babel version from CTAN? I think you have to clone and install it manually from GitHub.

**Comment by hpvd** [comment]
@amarakon that's great to hear :-)
I did a manual install directly using code from github, like I did for the updated linebreaker before.
Unfortunately, babel keep using the version from previous install....

**Comment by amarakon** [comment]
Actually I realized I did not have `linebreaker` loaded in my preamble upon testing it again. Once I load the package, the problem of the last line being the wrong direction persists. However, the issue with babel is fixed. @hpvd are you having the same issue as me?

**Comment by hpvd** [comment]
are you using latest linebreaker and checked with \listfiles comment at the beginning of the tex file the outputed package versions in the logfile - maybe you are doing the some thing like me but for linebreaker :-)

Maybe you can post your
- testing code and
- the result and
- an image of the log showing exact package versions used?

If both packages are used in latest version we have to reopen here.
(I couldn't get rid of old babel and this with new linebreaker the direction looks fine for me)

**Comment by michal-h21** [comment]
This is again the issue that we don't get the right paragraph direction in this case, you get the direction of the surrounding text, which is left to right. I don't think that there is a solution for this issue, other than explicit paragraph end before `\end{otherlanguage}`.

**Comment by hpvd** [comment]
@michal-h21 
looks like we have to reopen this issue and check compatibility to latest Babel..

btw linebreaker package seems not to have the meta information included used by listfiles command, like exact version and date

**Comment by hpvd** [comment]
> ...I don't think that there is a solution for this issue, other than explicit paragraph end before `\end{otherlanguage}`.

If so, couldn't/shouldn't this be done automatically by babel?

Do you understand the latest changes by babel?

**Comment by michal-h21** [comment]
The latest change in Babel solves just the multicolumn issue, I think. The problem here is that the `otherlanguage` environment can be used inside paragraphs, for mixing of languages, so I don't know how this issue could be solved without explicit paragraph end :/

**Comment by hpvd** [comment]
can confirm latest babel solved the multicolumn issue

**Comment by hpvd** [comment]
...but there seems to be another edgecase which produce problems when enabling linebreaker.
Opened a new issue see https://github.com/michal-h21/linebreaker/issues/9
